name: C++ Dynamic Input Add

on:
  workflow_dispatch:
    inputs:
      a:
        description: "Enter first number"
        required: true
        default: "10"
      b:
        description: "Enter second number"
        required: true
        default: "20"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Compile
        run: g++ add.cpp -o add

      - name: Run with input
        run: echo "${{ github.event.inputs.a }} ${{ github.event.inputs.b }}" | ./add
